version: '3.8'

services:
  httprequestwatcher:
    build:
      context: httprequestwatcher
      dockerfile: Dockerfile
    container_name: httprequestwatcher
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./env
    environment:
      - FLASK_ENV=development
  
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "5101:5101"
    restart: always
    env_file:
      - ./env
