version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
